Parameter dealer_Ф_make_deal : SellInfoP -> BuyInfoP -> SMLExpression (S:=Ledger) false ( XBool # XBool # uint128 ) uint . 
Parameter dealer_Ф_process_queue : uint -> uint -> SMLExpression (S:=Ledger) false True uint . 
Parameter DPrice_Ф_onTip3LendOwnership : uint128 -> uint32 -> uint256 -> uint256 -> XCell -> XAddress -> SMLExpression (S:=Ledger) false OrderRetP uint . 
Parameter DPrice_Ф_buyTip3 : uint128 -> XAddress -> SMLExpression (S:=Ledger) false OrderRetP uint . 
Parameter DPrice_Ф_processQueue : SMLExpression (S:=Ledger) false True uint . 
Parameter DPrice_Ф_cancelSell : SMLExpression (S:=Ledger) false True uint . 
Parameter DPrice_Ф_cancelBuy : SMLExpression (S:=Ledger) false True uint . 
Parameter DPrice_Ф_getDetails : SMLExpression (S:=Ledger) false DetailsInfoP uint . 
Parameter DPrice_Ф_getPrice : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getMinimumAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getTonsCfg : SMLExpression (S:=Ledger) false TonsConfigP uint . 
Parameter DPrice_Ф_getSells : SMLExpression (S:=Ledger) false ( XDictArray ) uint . 
Parameter DPrice_Ф_getBuys : SMLExpression (S:=Ledger) false ( XDictArray ) uint . 
Parameter DPrice_Ф_getSellAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getBuyAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getPrice : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getMinimumAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getTonsCfg : SMLExpression (S:=Ledger) false TonsConfigP uint . 
Parameter DPrice_Ф_getSells : SMLExpression (S:=Ledger) false ( XDictArray ) uint . 
Parameter DPrice_Ф_getBuys : SMLExpression (S:=Ledger) false ( XDictArray ) uint . 
Parameter DPrice_Ф_getSellAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getBuyAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getMinimumAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getTonsCfg : SMLExpression (S:=Ledger) false TonsConfigP uint . 
Parameter DPrice_Ф_getSells : SMLExpression (S:=Ledger) false ( XDictArray ) uint . 
Parameter DPrice_Ф_getBuys : SMLExpression (S:=Ledger) false ( XDictArray ) uint . 
Parameter DPrice_Ф_getSellAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getBuyAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getTonsCfg : SMLExpression (S:=Ledger) false TonsConfigP uint . 
Parameter DPrice_Ф_getSells : SMLExpression (S:=Ledger) false ( XDictArray ) uint . 
Parameter DPrice_Ф_getBuys : SMLExpression (S:=Ledger) false ( XDictArray ) uint . 
Parameter DPrice_Ф_getSellAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getBuyAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getSells : SMLExpression (S:=Ledger) false ( XDictArray ) uint . 
Parameter DPrice_Ф_getBuys : SMLExpression (S:=Ledger) false ( XDictArray ) uint . 
Parameter DPrice_Ф_getSellAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getBuyAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getBuys : SMLExpression (S:=Ledger) false ( XDictArray ) uint . 
Parameter DPrice_Ф_getSellAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getBuyAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getSellAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getBuyAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф_getBuyAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DPrice_Ф__fallback : XCell -> XSlice -> SMLExpression (S:=Ledger) false uint uint . 
Parameter DPrice_Ф_verify_tip3_addr : XAddress -> uint256 -> uint256 -> SMLExpression (S:=Ledger) false XBool uint . 
Parameter DPrice_Ф_expected_wallet_address : uint256 -> uint256 -> SMLExpression (S:=Ledger) false uint256 uint . 
Parameter DPrice_Ф_is_active_time : uint32 -> SMLExpression (S:=Ledger) false XBool uint . 
Parameter DPrice_Ф_on_sell_fail : uint -> ITONTokenWalletPtrP -> SMLExpression (S:=Ledger) false OrderRetP uint . 
Parameter DStock_Ф_constructor : uint256 -> uint128 -> uint128 -> uint128 -> uint128 -> uint128 -> uint128 -> uint128 -> uint8 -> XAddress -> SMLExpression (S:=Ledger) false True uint . 
Parameter DStock_Ф_setPairCode : XCell -> SMLExpression (S:=Ledger) false True uint . 
Parameter DStock_Ф_setPriceCode : XCell -> SMLExpression (S:=Ledger) false True uint . 
Parameter DStock_Ф_isFullyInitialized : SMLExpression (S:=Ledger) false XBool uint . 
Parameter DStock_Ф_getTonsCfg : SMLExpression (S:=Ledger) false TonsConfigP uint . 
Parameter DStock_Ф_getTradingPairCode : SMLExpression (S:=Ledger) false XCell uint . 
Parameter DStock_Ф_isFullyInitialized : SMLExpression (S:=Ledger) false XBool uint . 
Parameter DStock_Ф_getTonsCfg : SMLExpression (S:=Ledger) false TonsConfigP uint . 
Parameter DStock_Ф_getTradingPairCode : SMLExpression (S:=Ledger) false XCell uint . 
Parameter DStock_Ф_getTonsCfg : SMLExpression (S:=Ledger) false TonsConfigP uint . 
Parameter DStock_Ф_getTradingPairCode : SMLExpression (S:=Ledger) false XCell uint . 
Parameter DStock_Ф_getTradingPairCode : SMLExpression (S:=Ledger) false XCell uint . 
Parameter DStock_Ф_getSellPriceCode : XAddress -> SMLExpression (S:=Ledger) false XCell uint . 
Parameter DStock_Ф_getXchgPriceCode : XAddress -> XAddress -> SMLExpression (S:=Ledger) false XCell uint . 
Parameter DStock_Ф_getSellTradingPair : XAddress -> SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DStock_Ф_getMinAmount : SMLExpression (S:=Ledger) false uint128 uint . 
Parameter DStock_Ф_getDealsLimit : SMLExpression (S:=Ledger) false uint8 uint . 
Parameter DStock_Ф_getNotifyAddr : SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DStock_Ф_getDealsLimit : SMLExpression (S:=Ledger) false uint8 uint . 
Parameter DStock_Ф_getNotifyAddr : SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DStock_Ф_getNotifyAddr : SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DStock_Ф__fallback : XCell -> XSlice -> SMLExpression (S:=Ledger) false uint uint . 
Parameter DTradingPair_Ф_onDeploy : SMLExpression (S:=Ledger) false XBool uint . 
Parameter DTradingPair_Ф_getStockAddr : SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DTradingPair_Ф_getTip3Root : SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DTradingPair_Ф_onDeploy : SMLExpression (S:=Ledger) false XBool uint . 
Parameter DTradingPair_Ф_getStockAddr : SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DTradingPair_Ф_getTip3Root : SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DTradingPair_Ф_getStockAddr : SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DTradingPair_Ф_getTip3Root : SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DTradingPair_Ф_getTip3Root : SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DTradingPair_Ф__fallback : XCell -> XSlice -> SMLExpression (S:=Ledger) false uint uint . 
Parameter DFLeXClient_Ф_constructor : uint256 -> XCell -> SMLExpression (S:=Ledger) false True uint . 
Parameter DFLeXClient_Ф_setStockCfg : TonsConfigP -> XAddress -> XAddress -> SMLExpression (S:=Ledger) false True uint . 
Parameter DFLeXClient_Ф_deployTradingPair : XAddress -> XAddress -> uint128 -> uint128 -> SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DFLeXClient_Ф_deployPriceWithSell : XCell -> SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DFLeXClient_Ф_deployPriceWithBuy : XCell -> SMLExpression (S:=Ledger) false XAddress uint . 
Parameter DFLeXClient_Ф_cancelSellOrder : XCell -> SMLExpression (S:=Ledger) false True uint . 
Parameter DFLeXClient_Ф_cancelBuyOrder : XCell -> SMLExpression (S:=Ledger) false True uint . 
Parameter DFLeXClient_Ф_getOwner : SMLExpression (S:=Ledger) false uint256 uint . 
Parameter DFLeXClient_Ф__fallback : XCell -> XSlice -> SMLExpression (S:=Ledger) false uint uint . 
Parameter DFLeXClient_Ф_preparePrice : uint128 -> uint128 -> uint8 -> Tip3ConfigP -> XCell -> SMLExpression (S:=Ledger) false ( StateInitP # XAddress # uint256 ) uint . 
Parameter Ф_prepare_price_state_init_and_addr : DPriceP -> XCell -> SMLExpression (S:=Ledger) false ( StateInitP # uint256 ) uint . 
Parameter Ф_prepare_trading_pair_state_init_and_addr : DTradingPairP -> XCell -> SMLExpression (S:=Ledger) false ( StateInitP # uint256 ) uint . 
Parameter Ф_calc_cost : uint128 -> uint128 -> SMLExpression (S:=Ledger) false ( XMaybe uint128 ) uint . 
Parameter Ф_process_queue_impl : XAddress -> IStockNotifyPtrP -> uint128 -> uint8 -> TonsConfigP -> uint -> uint -> uint128 -> ( XQueue SellInfoP -> uint128 -> ( XQueue BuyInfoP -> SMLExpression (S:=Ledger) false process_retP uint . 

